# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

POST http://localhost:8000/api/programs/chat
Accept: application/json
Content-Type: application/json

{
    "query": "What CDU wants to do for illegal immigration??"
}

###
