# Test your FastAPI endpoints

# Chat completion first message
POST {{host}}/api/chat/completion
Accept: application/json
Content-Type: application/json
Authorization: Basic {{basic_auth}}

{
  "history": [
    {
      "role": "You",
      "content": "What CDU wants to do for economy?"
    }
  ],
  "question": "What CDU wants to do for economy?"
}

###

# Chat completion with history
POST {{host}}/api/chat/completion
Accept: application/json
Content-Type: application/json
Authorization: Basic {{basic_auth}}

{
  "history": [
    {
      "role": "You",
      "content": "Was will die AfD gegen die Wirtschaftskrise tun?"
    },
    {
      "role": "AI",
      "content": "Die AfD will die zunehmende Plan- und Subventionswirtschaft der letzen Jahrzehnte in eine moderne sozialer Marktwirtschaft zurückführen, um alle kommenden Herausforderungen, einschliesslich der Wirtschaftskrise, meistern zu können. Sie will auch den Abbau der überschwänglichen Bürokratie bei der Dokumentation in der Forstwirtschaft umsetzen. (Maximal zwei Sätze)"
    },
    {
      "role": "You",
      "content": "Was habe ich Sie in der vorherigen Frage gefragt?"
    }
  ],
  "question": "Was habe ich Sie in der vorherigen Frage gefragt?"
}

###
# Most relevant chunks retrieval
POST {{host}}/api/chat/retrieve
Accept: application/json
Content-Type: application/json
Authorization: Basic {{basic_auth}}

{
  "question": "Was denkt die AfD über Einwanderer??"
}

###
