# Test your FastAPI endpoints

POST {{host}}/api/chat/completion
Accept: application/json
Content-Type: application/json
Authorization: Basic {{basic_auth}}

{
  "history": [
    {
      "role": "You",
      "content": "What CDU wants to do for economy?"
    }
  ],
  "query": "What CDU wants to do for economy?"
}

###

POST {{host}}/api/chat/retrieve
Accept: application/json
Content-Type: application/json
Authorization: Basic {{basic_auth}}

{
  "query": "What CDU wants to do for economy?",
   "history": []
}

###
